### ISSUE TITLE
full example

### ISSUE THREAD

**Issue by pifuant** [Jeff-Tian/egg-grpc-client-ts#7]
你好， 可以给一个完整的demo参考下不

**Comment by Jeff-Tian** [comment]
我周末有时间的话，可以弄一个

**Comment by pifuant** [comment]
@Jeff-Tian  十分感谢

**Comment by Jeff-Tian** [comment]
写了个完整的 demo: https://github.com/Jeff-Tian/egg-grpc-client-ts-example ，请参考。

其实在这个项目的测试目录下，已经有一个最简单的 js 版本 demo：https://github.com/Jeff-Tian/egg-grpc-client-ts/tree/master/test/fixtures/apps/grpc-client-test。

**Comment by pifuant** [comment]
非常感谢
